const shopActionTypes = {
  FETCHING_COLLECTION_STARTS: `FETCHING_COLLECTION_STARTS`,
  FETCHING_COLLECTION_SUCCESS: `FETCHING_COLLECTION_SUCCESS`,
  FETCHING_COLLECTION_FAILURE: `FETCHING_COLLECTION_FAILURE`
}

export default shopActionTypes;
